[DOCUMENTATION]
ORG_NAME="Turkish Token"
ORG_URL="https://raconsuz5.github.io/TRK/"
ORG_DESCRIPTION="The official token of TRK on Stellar"
ORG_LOGO="https://raconsuz5.github.io/.well-known/logo.png"

[[CURRENCIES]]
code="TURKCOIN"  # Token Kodu
issuer="GDY4NEGSVV7YKX33OF4JRASYAMLYU5DCKVXWKEBM3XTWAK7HZ4JZSUQY"  # Stellar Token Adresi (Değiştir!)
status="live"  # "live" veya "test"
display_decimals=2  # Virgülden sonra kaç basamak gösterilecek
image="https://raconsuz5.github.io/.well-known/icon.png"
